list_targ = [
"../img/Targets/living_room/sun_asiojdegqcvrpizr.jpg",
"../img/Targets/living_room/sun_bojvcngymrqdthde.jpg",
"../img/Targets/living_room/sun_bpwitdjuouxtqeya.jpg",
"../img/Targets/living_room/sun_anbdspwawzgrwnla.jpg",
"../img/Targets/living_room/sun_bwibbhtejiewqjss.jpg",
"../img/Targets/living_room/sun_beyiaxemhyjtpcmo.jpg",
"../img/Targets/living_room/sun_brznthqkhumnbwxj.jpg",
"../img/Targets/living_room/sun_biiobaofvszgqpkm.jpg",
"../img/Targets/living_room/sun_arinhqnywjqrtrhf.jpg",
"../img/Targets/living_room/sun_bfrwtvtaqrroyjao.jpg",
"../img/Targets/living_room/sun_aygkoljubkyhhycy.jpg",
"../img/Targets/living_room/sun_bltwdmjxaxlwyido.jpg",
"../img/Targets/living_room/sun_bhpxikxxkuopazhu.jpg",
"../img/Targets/living_room/sun_abmhxsodaptaogbq.jpg",
"../img/Targets/living_room/sun_bucertsbpntzdgea.jpg",
"../img/Targets/living_room/sun_bqnoehkoidwdyyjw.jpg",
"../img/Targets/living_room/sun_blxswaxpoupgwihl.jpg",
"../img/Targets/living_room/sun_bgwmiqwlreupuwqs.jpg",
"../img/Targets/living_room/sun_buqhudkagyzwriny.jpg",
"../img/Targets/living_room/sun_akgsgfelkaxhkmgo.jpg",
"../img/Targets/living_room/sun_brtjjtkybllyzemz.jpg",
"../img/Targets/living_room/sun_bquxzyutkrbxihsp.jpg",
"../img/Targets/living_room/sun_bkaeugvancwoiknl.jpg",
"../img/Targets/living_room/sun_bbrxjlbkfmnjtxiz.jpg",
"../img/Targets/living_room/sun_bjdftnlhsazvmjuy.jpg",
"../img/Targets/living_room/sun_bbjpwjobjhuarxzr.jpg",
"../img/Targets/living_room/sun_bndbkdzixliunlbz.jpg",
"../img/Targets/living_room/sun_bthcwkgnrrlojmek.jpg",
"../img/Targets/living_room/sun_bxccnqqjzijidinf.jpg",
"../img/Targets/living_room/sun_bvvzfxfasatrxqfm.jpg",
"../img/Targets/living_room/sun_bnhqckgknuryydtg.jpg",
"../img/Targets/living_room/sun_blfoisnvweqrqima.jpg",
"../img/Targets/living_room/sun_aufspxbtqorylcna.jpg",
"../img/Targets/living_room/sun_ajvylnkvejnlprts.jpg",
"../img/Targets/living_room/sun_acdgufoamnnvlkuy.jpg",
"../img/Targets/living_room/sun_bwjmvyylrpeeqydh.jpg",
"../img/Targets/living_room/sun_bfhvvwgvxxjrctil.jpg",
"../img/Targets/living_room/sun_bmhyvtokbpztqmsm.jpg",
"../img/Targets/living_room/sun_boqyvpiuwzsfjplc.jpg",
"../img/Targets/living_room/sun_befrbcslctncdtls.jpg"
]



list_filler = [
"../img/Fillers/living_room/sun_aaqvvjdycgpjbdzq.jpg",
"../img/Fillers/living_room/sun_aasothdstfehplzt.jpg",
"../img/Fillers/living_room/sun_aavtbadenwnzeutj.jpg",
"../img/Fillers/living_room/sun_abdeycdjphjbrrvw.jpg",
"../img/Fillers/living_room/sun_abemoamznrwmirdc.jpg",
"../img/Fillers/living_room/sun_abgqzazaolortwzc.jpg",
"../img/Fillers/living_room/sun_abjobegxwfmqwyll.jpg",
"../img/Fillers/living_room/sun_abjtezvuynsqmgzp.jpg",
"../img/Fillers/living_room/sun_acejajfxwnwkukkx.jpg",
"../img/Fillers/living_room/sun_acfzhwqjvlkdirxy.jpg",
"../img/Fillers/living_room/sun_acihtuncjgfjrbwg.jpg",
"../img/Fillers/living_room/sun_acqkbisecrfnxdqz.jpg",
"../img/Fillers/living_room/sun_acyfecznustmuiqe.jpg",
"../img/Fillers/living_room/sun_addinypctrsdgwya.jpg",
"../img/Fillers/living_room/sun_addkyazrqpmdesxd.jpg",
"../img/Fillers/living_room/sun_adeozewhklbmfscj.jpg",
"../img/Fillers/living_room/sun_adgsgxlewpwsithr.jpg",
"../img/Fillers/living_room/sun_adgznedqehchqxkg.jpg",
"../img/Fillers/living_room/sun_adltyrtblxngmaze.jpg",
"../img/Fillers/living_room/sun_aefyrchnbsshaooz.jpg",
"../img/Fillers/living_room/sun_aekgbypbglabbybh.jpg",
"../img/Fillers/living_room/sun_aepeoohdzjpxoixu.jpg",
"../img/Fillers/living_room/sun_aewwidbjljnhruhr.jpg",
"../img/Fillers/living_room/sun_aeyhsysudobwikuw.jpg",
"../img/Fillers/living_room/sun_afciptxtzzckygby.jpg",
"../img/Fillers/living_room/sun_afkajzuxvaabufkg.jpg",
"../img/Fillers/living_room/sun_aflrhkzrzqbuvzpm.jpg",
"../img/Fillers/living_room/sun_afnwwltwbnosxqeq.jpg",
"../img/Fillers/living_room/sun_afpkjzjbvuxrlqdy.jpg",
"../img/Fillers/living_room/sun_afsisumaqfamduuw.jpg",
"../img/Fillers/living_room/sun_agmjbbohaltznbuv.jpg",
"../img/Fillers/living_room/sun_agtyeksoutpcusyb.jpg",
"../img/Fillers/living_room/sun_agvagdqeqxgjjnuv.jpg",
"../img/Fillers/living_room/sun_agysmjmzyutkejnc.jpg",
"../img/Fillers/living_room/sun_ahlaragoykbsjgaj.jpg",
"../img/Fillers/living_room/sun_ahogocjizmafcsyt.jpg",
"../img/Fillers/living_room/sun_ahtyouadxfbfttcx.jpg",
"../img/Fillers/living_room/sun_ahxntniovyyimurs.jpg",
"../img/Fillers/living_room/sun_aiiwfbymtsnmjoed.jpg",
"../img/Fillers/living_room/sun_ajmbckjbjjrlqvbj.jpg"
]


list_targ_tutorial = [
"../img/Targets/kitchen/sun_ailrmhyjajxxfwjh.jpg",
"../img/Targets/kitchen/sun_aqftpyuksqtdtceh.jpg",
"../img/Targets/kitchen/sun_azxetkujrgobhzbi.jpg",
"../img/Targets/kitchen/sun_auyrvbsgjzcbllwy.jpg",
"../img/Targets/kitchen/sun_auwldxtolpavypst.jpg",
"../img/Targets/kitchen/sun_ateoptjjakachbou.jpg",
"../img/Targets/kitchen/sun_akxcpkquuuxdiqwv.jpg"
]

list_filler_tutorial = [
"../img/Fillers/kitchen/sun_aadbddgrdsjugojn.jpg",
"../img/Fillers/kitchen/sun_aaebjpeispxohmfv.jpg",
"../img/Fillers/kitchen/sun_aaeggavxrhahhhsp.jpg",
"../img/Fillers/kitchen/sun_aahxnzrpowefyvrp.jpg",
"../img/Fillers/kitchen/sun_aajnubwzelxjzhxh.jpg",
"../img/Fillers/kitchen/sun_aamedkxepzlwuxes.jpg"
]